name: 构建检查

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 安装 pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: 设置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: 验证文件结构
        run: |
          echo "当前目录内容:"
          dir
          echo "检查 zebar/hyprglaze-bar 目录:"
          dir zebar\hyprglaze-bar
          echo "检查 pnpm-lock.yaml 文件:"
          if (Test-Path "zebar\hyprglaze-bar\pnpm-lock.yaml") {
            echo "✅ pnpm-lock.yaml 存在"
          } else {
            echo "❌ pnpm-lock.yaml 不存在"
          }

      - name: 获取 pnpm store 目录
        shell: pwsh
        run: |
          cd zebar\hyprglaze-bar
          $storePath = pnpm store path --silent
          echo "STORE_PATH=$storePath" >> $env:GITHUB_ENV
          echo "Store path: $storePath"

      - name: 设置 pnpm 缓存
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('zebar/hyprglaze-bar/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: 安装依赖
        shell: pwsh
        run: |
          cd zebar\hyprglaze-bar
          echo "当前目录: $(Get-Location)"
          echo "检查 pnpm-lock.yaml:"
          if (Test-Path "pnpm-lock.yaml") {
            echo "✅ 找到 pnpm-lock.yaml"
          } else {
            echo "❌ 未找到 pnpm-lock.yaml"
            exit 1
          }
          pnpm install --frozen-lockfile

      - name: 构建项目
        shell: pwsh
        run: |
          cd zebar\hyprglaze-bar
          pnpm build
